// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQM0c14C0WUdgfEewNAlpRPDupMqZDnAk',
    appId: '1:932020071160:web:d08da439d295d23f60290d',
    messagingSenderId: '932020071160',
    projectId: 'flutterauthen-b091b',
    authDomain: 'flutterauthen-b091b.firebaseapp.com',
    storageBucket: 'flutterauthen-b091b.appspot.com',
    measurementId: 'G-0LKH5REQB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfj3d_pmB2Lrg7oFOfEY6f4WHPpQTmx_s',
    appId: '1:932020071160:android:42db19442636ab4860290d',
    messagingSenderId: '932020071160',
    projectId: 'flutterauthen-b091b',
    storageBucket: 'flutterauthen-b091b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcjMexKiY5oDnNoUGs1korz3zqA3QJFhg',
    appId: '1:932020071160:ios:599de3824890713d60290d',
    messagingSenderId: '932020071160',
    projectId: 'flutterauthen-b091b',
    storageBucket: 'flutterauthen-b091b.appspot.com',
    iosBundleId: 'com.example.authen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcjMexKiY5oDnNoUGs1korz3zqA3QJFhg',
    appId: '1:932020071160:ios:599de3824890713d60290d',
    messagingSenderId: '932020071160',
    projectId: 'flutterauthen-b091b',
    storageBucket: 'flutterauthen-b091b.appspot.com',
    iosBundleId: 'com.example.authen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQM0c14C0WUdgfEewNAlpRPDupMqZDnAk',
    appId: '1:932020071160:web:9bee3271f028530f60290d',
    messagingSenderId: '932020071160',
    projectId: 'flutterauthen-b091b',
    authDomain: 'flutterauthen-b091b.firebaseapp.com',
    storageBucket: 'flutterauthen-b091b.appspot.com',
    measurementId: 'G-MS0JN4QZSW',
  );
}
